name: nfc_manager_felica
description: A Flutter package providing a FeliCa abstraction built on top of `nfc_manager`.
version: 1.0.0
repository: https://github.com/okadan/flutter-nfc-manager-felica

environment:
  sdk: ^3.9.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  nfc_manager: ^4.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
